#!/usr/bin/env bash

input="$1"
shift
output="$1"
shift

if [ -n "$MDTOPDF_DEFAULTS" ]; then
	defaults="--defaults=$MDTOPDF_DEFAULTS"
fi

if [ -n "$MDTOPDF_DATADIR" ]; then
	data_dir="--data-dir=$MDTOPDF_DATADIR"
fi

pandoc --standalone "$input" -o "$output" \
	${defaults+"$defaults"} ${data_dir+"$data_dir"} $MDTOPDF_ARGS \
	"$@"
